### create user
POST http://localhost:3009/api/user/register HTTP/1.1
content-type: application/json

{
    "firstname": "House",
    "lastname": "sample",
    "email": "sample@example.com",
    "mobile": "09087876545",
    "password": "password"
}
